name: Close PR when Build Fail
on:
  pull_request:
    types: [ opened ]
    branches: [ 'main' ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    steps:
      - name: If build fail
        # 이전 step이 실패한 경우에만 이 step을 실행시키는 syntax
#        if: ${{ failure() }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.ROBINJOON_GITHUB_TOKEN }}
          script: |
            const pull_number = ${{ github.event.pull_request.number }}
            const updated_title = `[BUILD FAIL] ${{ github.event.pull_request.title }}`
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              title: updated_title,
              state: 'closed'
            })